config/routes.rb
Agenda::Application.routes.draw do
  resources :contactos

  devise_for :users
	  root :to => "home#index"
    

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
    devise :database_authenticatable

    before_create :init_devise_password

   
# slffalfkaefjlkeaie
    def init_devise_password
        password = Devise.friendly_token[0,20]
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#asssss
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]


  # GET /contactos
  # GET /contactos.xml
  def index
    @contactos = Contacto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contactos }
    end
  end

  # GET /contactos/1
  # GET /contactos/1.xml
  #aslfjeiieiejej
  def show
    @contacto = Contacto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contacto }
    end
  end

  # GET /contactos/new
  # GET /contactos/new.xml
  def new
    @contacto = Contacto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contacto }
    end
  end

  # GET /contactos/1/edit
  def edit
    @contacto = Contacto.find(params[:id])
  end

  # POST /contactos
  # POST /contactos.xml
  def create
    @contacto = Contacto.new(params[:contacto])
#probando
#askfejwiiwi
    respond_to do |format|
      if @contacto.save
        format.html { redirect_to(@contacto, :notice => 'Contacto was successfully created.') }
        format.xml  { render :xml => @contacto, :status => :created, :location => @contacto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contacto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contactos/1
  # PUT /contactos/1.xml
  def update
    @contacto = Contacto.find(params[:id])

    respond_to do |format|
      if @contacto.update_attributes(params[:contacto])
        format.html { redirect_to(@contacto, :notice => 'Contacto was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contacto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1
  # DELETE /contactos/1.xml
  def destroy
    @contacto = Contacto.find(params[:id])
    @contacto.destroy

    respond_to do |format|
      format.html { redirect_to(contactos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/views/contactos/_form.html.erb
<%= form_for(@contacto) do |f| %>
  <% if @contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacto.errors.count, "error") %> METENDO O DEDO DONDE NON ME CHAMAN:</h2>

      <ul>
      <% @contacto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br />
    <%= f.text_area :apellidos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editing contacto</h1>

<%= render 'form' %>

<%= link_to 'Show', @contacto %> |
<%= link_to 'Back', contactos_path %>

app/views/contactos/index.html.erb
<h1>Listing contactos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Telefono</th>
    <th>Apellidos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contactos.each do |contacto| %>
  <tr>
    <td><%= contacto.nombre %></td>
    <td><%= contacto.telefono %></td>
    <td><%= contacto.apellidos %></td>
    <td><%= link_to 'Show', contacto %></td>
    <td><%= link_to 'Edit', edit_contacto_path(contacto) %></td>
    <td><%= link_to 'Destroy', contacto, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contacto', new_contacto_path %>

app/views/contactos/new.html.erb
<h1>New contacto</h1>

<%= render 'form' %>

<%= link_to 'Back', contactos_path %>

app/views/contactos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @contacto.nombre %>
</p>

<p>
  <b>Telefono:</b>
  <%= @contacto.telefono %>
</p>

<p>
  <b>Apellidos:</b>
  <%= @contacto.apellidos %>
</p>


<%= link_to 'Edit', edit_contacto_path(@contacto) %> |
<%= link_to 'Back', contactos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div> 
<%= yield %>

</body>
</html>